name: Android CI

on:
  push:
    branches: [ chore/setup_github_action_ci ]
  pull_request:
    branches: [ chore/setup_github_action_ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      working-directory: ./AndroidWallpaper
      run: chmod +x gradlew
    - name: Build with Gradle
      working-directory: ./AndroidWallpaper
      run: ./gradlew build
